apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: instana-agent
    meta.helm.sh/release-namespace: instana-agent
  labels:
    app.kubernetes.io/instance: instana-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: instana-agent
    app.kubernetes.io/version: 1.2.67
    helm.sh/chart: instana-agent-1.2.67
  name: instana-agent
  namespace: instana-agent
spec:
  clusterIP: 10.0.145.95
  clusterIPs:
  - 10.0.145.95
  internalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: agent-apis
    port: 42699
    protocol: TCP
    targetPort: 42699
  selector:
    app.kubernetes.io/instance: instana-agent
    app.kubernetes.io/name: instana-agent
  sessionAffinity: None
  type: ClusterIP
